### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by antash-mishra** [corrodedlabs/coyote#4]
- [ ] Creating web UI for command line tool 
  >Seed framework (ongoing discussion)
- [ ] Checking RSS feed and creating tool for RSS feed
- [ ] Creating multi-threaded command line tool

**Comment by shakdwipeea** [comment]
@antash-mishra  let's make these three separate issues
